wandb_version: 1

experiment:
  desc: null
  value:
    run_name: windfarm_debug
    log_dir: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/logging/
    model_ckpt_dir: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/logging/windfarm_debug_32c68774
dataset:
  desc: null
  value:
    dataset_class: wind_forecasting.datasets.wind_farm.KPWindFarm
    data_path: /Users/ahenry/Documents/toolboxes/wind_forecasting/examples/data/normalized_data.parquet
    context_len: 120
    target_len: 120
    target_turbine_ids:
    - wt029
    - wt034
    - wt074
    normalize: false
    batch_size: 128
    workers: 6
    overfit: false
    test_split: 0.15
    val_split: 0.15
    collate_fn: null
    dataset_kwargs:
      target_turbine_ids:
      - wt029
      - wt034
      - wt074
model:
  desc: null
  value:
    model_class: wind_forecasting.models.spacetimeformer.spacetimeformer.spacetimeformer_model.spacetimeformer_model.Spacetimeformer_Forecaster
    embed_size: 32
    num_layers: 3
    heads: 4
    forward_expansion: 4
    output_size: 1
callbacks:
  desc: null
  value: {}
training:
  desc: null
  value:
    grad_clip_norm: 0.0
    limit_val_batches: 1.0
    val_check_interval: 1.0
    debug: false
    accumulate: 1.0
    max_epochs: 100
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731255413
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 13
      - 16
      - 23
      4: 3.12.4
      5: 0.17.4
      8:
      - 5
      13: darwin-arm64
